### ISSUE TITLE
SVG parser crashes on elliptical-arc-argument within path element.

### ISSUE THREAD

**Issue by mkuehne-git** [blackears/svgSalamander#107]
# Issue
The following SVG icon crashes the application with `IllegalStateException`. The SVG itself renders nicely within a browser.

```svg
<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
  <path stroke-linecap="round" stroke-linejoin="round" d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z" />
  <path stroke-linecap="round" stroke-linejoin="round" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
</svg>
```

This is the `IllegalStateException`
```cmd
Caused by: java.lang.IllegalStateException: Unexpected element while parsing cmd 'a' encountered token '' rest=z (index=33 in input=M21 12a9 9 0 11-18 0 9 9 0 0118 0z)
	at com.kitfox.svg.pathcmd.PathParser.nextFloat(PathParser.java:139)
	at com.kitfox.svg.pathcmd.PathParser.parsePathCommand(PathParser.java:197)
```
# Analysis
The exception is caused within the method  `com.kitfox.svg.pathcmd.PathParser.parsePathCommand()`, namely the line `nextFloat() == 1f, nextFloat() == 1f,`. 

```java
case 'a':
    cmd = new Arc(true, nextFloat(), nextFloat(),
        nextFloat(),
        nextFloat() == 1f, nextFloat() == 1f,
        nextFloat(), nextFloat());
    break;
```

According to [W3C](https://www.w3.org/TR/SVG11/paths.html) the `elliptical-arc-argument` is not a `float` but a `flag`, represented by a single digit '0' or '1'. And the `comma-wsp` separator between the two flags is **optional**.

```
elliptical-arc-argument:
    nonnegative-number comma-wsp? nonnegative-number comma-wsp? 
        number comma-wsp flag comma-wsp? flag comma-wsp? coordinate-pair
...
flag:
    "0" | "1"
comma-wsp:
    (wsp+ comma? wsp*) | (comma wsp*)
```

**Comment by blackears** [comment]
Fix has been merged.
