### ISSUE TITLE
build problems

### ISSUE THREAD

**Issue by cbfiddle** [blackears/svgSalamander#17]
It has been a while since I have tried to build svgSalamander.
I do not see any instructions on how to do that, so I ran ant in the svg-core directory.
It failed here:

-do-test-run:
    [junit] WARNING: multiple versions of ant detected in path for junit 
    [junit]          jar:file:/usr/local/ant/lib/ant.jar!/org/apache/tools/ant/Project.class
    [junit]      and jar:file:/Volumes/L/Java/svgSalamander/repo/libraries/ant.jar!/org/apache/tools/ant/Project.class
    [junit] Exception in thread "main" java.lang.NoSuchMethodError: org.apache.tools.ant.util.FileUtils.close(Ljava/io/Writer;)V
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.registerTestCase(JUnitTestRunner.java:1212)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:934)
    [junit] Testsuite: com.kitfox.salamander.javascript.JSTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
    [junit] 
    [junit] Testcase: com.kitfox.salamander.javascript.JSTest:BeforeFirstTest:	Caused an ERROR
    [junit] Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] junit.framework.AssertionFailedError: Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] 
    [junit] 
    [junit] Test com.kitfox.salamander.javascript.JSTest FAILED (crashed)

**Comment by blackears** [comment]
I've removed the tests as they're not actually being used.  If you compile the default target, it should work (although the javadoc will still generate an error).

**Comment by cbfiddle** [comment]
I still get the same failure running the default target.

I think the error occurs before any tests are run.

-do-test-run:
    [junit] WARNING: multiple versions of ant detected in path for junit 
    [junit]          jar:file:/usr/local/ant/lib/ant.jar!/org/apache/tools/ant/Project.class
    [junit]      and jar:file:/Volumes/L/Java/svgSalamander/repo/libraries/ant.jar!/org/apache/tools/ant/Project.class
    [junit] Exception in thread "main" java.lang.NoSuchMethodError: org.apache.tools.ant.util.FileUtils.close(Ljava/io/Writer;)V
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.registerTestCase(JUnitTestRunner.java:1212)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:934)
    [junit] Testsuite: com.kitfox.salamander.javascript.JSTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
    [junit] 
    [junit] Testcase: com.kitfox.salamander.javascript.JSTest:BeforeFirstTest:	Caused an ERROR
    [junit] Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] junit.framework.AssertionFailedError: Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] 
    [junit] 
    [junit] Test com.kitfox.salamander.javascript.JSTest FAILED (crashed)


The jar target works.

**Comment by cbfiddle** [comment]
Looks like I did not have the latest files when I made my previous test.

However, I still get an error using the default target:

BUILD FAILED
/Volumes/L/Java/svgSalamander/repo/svg-core/nbproject/build-impl.xml:1329: The following error occurred while executing this line:
/Volumes/L/Java/svgSalamander/repo/svg-core/nbproject/build-impl.xml:344: srcdir "/Volumes/L/Java/svgSalamander/repo/svg-core/src/test/java" does not exist!

**Comment by cbfiddle** [comment]
An unrelated question:

Is there a reason why these files are tracked by git?

	modified:   ../www/binaries/svgSalamander-tiny.jar
	modified:   ../www/binaries/svgSalamander.jar

It means every build creates a change that needs to be committed (or discarded).

**Comment by cbfiddle** [comment]
Another unrelated issue: in the latest set of changes, I am seeing stray ^M-s in the diffs.

**Comment by blackears** [comment]
The binaries are tracked by Git because this project used to be hosted on java.net and they had a system for a while where you checked the site webpage directly into the source tree.  This is a holdover from that.  It's not really useful any more, but I thought people might want to just grab a compiled binary instead of compiling it themselves.

**Comment by blackears** [comment]
What are the ^M?  Are those carriage returns?

**Comment by cbfiddle** [comment]
I believe so.

**Comment by cbfiddle** [comment]
There must be a better way to provide binaries that as tracked files in git.

**Comment by blackears** [comment]
I've added an instruction to the ant file that should create the directory if is it missing.  Let me know if this fixes the problem.  It is not happening on my machine.

**Comment by cbfiddle** [comment]
Yes, that fixes the problem. Now it gets to javadoc and fails there, which sounds like something you already are aware of.
