### ISSUE TITLE
Ruby icon failed to render

### ISSUE THREAD

**Issue by VISTALL** [blackears/svgSalamander#83]
Hello. I catch this problem.

Original icon from wiki (https://upload.wikimedia.org/wikipedia/commons/7/73/Ruby_logo.svg)

![](https://upload.wikimedia.org/wikipedia/commons/7/73/Ruby_logo.svg)

Render throw exception:

```
Caused by: com.kitfox.svg.SVGException: java.lang.IllegalArgumentException: Keyframe fractions must be increasing: 0.0
	at com.kitfox.svg.ShapeElement.renderShape(ShapeElement.java:169)
```

I reexport this icon in Illustrator with plain options(svg1., no css, etc). And got this exception:

(svg code https://gist.github.com/VISTALL/3ba9af463cfce543e918a82f55855691)

```
Exception in thread "main" java.awt.geom.IllegalPathStateException: missing initial moveto in path definition
	at java.awt.geom.Path2D$Float.needRoom(Path2D.java:323)
	at java.awt.geom.Path2D.closePath(Path2D.java:1876)
	at com.kitfox.svg.pathcmd.Terminal.appendPath(Terminal.java:65)
```

All icons rendered in Illustrator/Chrome correctly 

Thanks

**Comment by blackears** [comment]
I've pushed a change which fixes this.  Let me know if you continue to have issues.

**Comment by VISTALL** [comment]
@blackears thanks! Original icon works as expected. But reimported - not, failed.

**Comment by blackears** [comment]
I don't know what you mean by "reexported - not, failed."

**Comment by VISTALL** [comment]
1. Opened original Ruby logo in Illustrator.
2. File -> Save as...
3. Choose svg 1.0, disable all checkboxes, and disable css styling.
4. Save file.

Result this svg code https://gist.github.com/VISTALL/3ba9af463cfce543e918a82f55855691 which is failed for render

**Comment by blackears** [comment]
It should work now.

**Comment by VISTALL** [comment]
Yeah, works as expected. Thanks :)
